Pandas-DataFrame and Series

Pandas is a powerful data manipulation library in python, widely used for "Data analysis and Data cleaning". It provides two primary data structure: Series and DataFrame. A Series is a 1D array like object, while a DataFrame is a 2D, size-mutable and potentially heterogeneous tabular data structure with labled axes(row and columns).

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\administrator\dataanalyst\venv\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\administrator\dataanalyst\venv\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\administrator\dataanalyst\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\administrator\dataanalyst\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\administrator\dataanalyst\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
# Series
# Pandas Series is a 1-D array-like object that can hold any data type. It is similar to a column in a spreadsheet or a SQL table.
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
# create a Series from a dictionary
data = {'a': 10, 'b': 20, 'c': 30} # a, b, c are indices and 10, 20, 30 are values
series_dict = pd.Series(data) 
print("Series from dictionary \n", series_dict)

Series from dictionary
 a    10
b    20
c    30
dtype: int64

In [6]:
data = [10, 20, 30, 40, 50]
indexes = ['a', 'b', 'c', 'd', 'e']
pd.Series(data, index=indexes)

a    10
b    20
c    30
d    40
e    50
dtype: int64

DataFrame

In [7]:
# DataFrame
# Create a DataFrame from a dictionary of lists
data = { 'Name': ['Alice', 'Bob', 'Charlie', 'David'],
         'Age': [24, 27, 22, 32],
         'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'] 
       }
df = pd.DataFrame(data)
print("DataFrame \n", df)
print(type(df))

DataFrame
       Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
<class 'pandas.DataFrame'>

In [8]:
# Create a DataFrame from a list of dictionaries
data = [ {'Name': 'Alice', 'Age': 24, 'City': 'New York'},
         {'Name': 'Bob', 'Age': 27, 'City': 'Los Angeles'},
         {'Name': 'Charlie', 'Age': 22, 'City': 'Chicago'},
         {'Name': 'David', 'Age': 32, 'City': 'Houston'} 
       ]
df=pd.DataFrame(data)
print("DataFrame from list of dictionaries \n", df)
print(type(df))

DataFrame from list of dictionaries
       Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
<class 'pandas.DataFrame'>

In [9]:
# Read CSV file into DataFrame
df=pd.read_csv('products-100.csv')
df.head(5) # display first 5 rows
df.tail(5) # display last 5 rows

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [10]:
# Accessing Data from DataFrame
df['Name'] # Access 'Name' column

0      Compact Printer Air Advanced Digital
1                                    Tablet
2                      Smart Blender Cooker
3              Advanced Router Rechargeable
4              Portable Mouse Monitor Phone
                      ...
95                                   Router
96       Fast Thermostat Microphone Scooter
97    Eco Heater Toaster Stove Silent Sense
98                 Clean Blender Scale Lite
99                               Smart Lamp
Name: Name, Length: 100, dtype: str

In [11]:
df.loc[0] # Access first row by label

Index                                                       1
Name                     Compact Printer Air Advanced Digital
Description     Situation organization these memory much off.
Brand                                 Garner, Boyle and Flynn
Category                                   Books & Stationery
Price                                                     265
Currency                                                  USD
Stock                                                     774
EAN                                             2091465262179
Color                                             ForestGreen
Size                                                    Large
Availability                                        pre_order
Internal ID                                                56
Name: 0, dtype: object

In [12]:
df.iloc[0] # Access first row by integer location

Index                                                       1
Name                     Compact Printer Air Advanced Digital
Description     Situation organization these memory much off.
Brand                                 Garner, Boyle and Flynn
Category                                   Books & Stationery
Price                                                     265
Currency                                                  USD
Stock                                                     774
EAN                                             2091465262179
Color                                             ForestGreen
Size                                                    Large
Availability                                        pre_order
Internal ID                                                56
Name: 0, dtype: object

In [13]:
df

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [14]:
# Accessing a specified element
df.at[2, 'Age']  # Access element at third row and 'Age'

KeyError: 'Age'

In [ ]:
# Accessing a specified element using iat
df.iat[1, 2]  # Access element at second row and third column

'Los Angeles'

In [ ]:
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [ ]:
# Data Manipulation with DataFrame
# Adding a new column
df['Salary'] = [50000, 60000, 55000, 70000]
df

      Name  Age         City  Salary
0    Alice   24     New York   50000
1      Bob   27  Los Angeles   60000
2  Charlie   22      Chicago   55000
3    David   32      Houston   70000

In [ ]:
# Removing a column
df.drop('Salary', axis=1, inplace=True) # axis=1 indicates column, inplace=True modifies the original DataFrame
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [ ]:
df['Age'] = df['Age'] + 1  # Increment age by 1
df

      Name  Age         City
0    Alice   25     New York
1      Bob   28  Los Angeles
2  Charlie   23      Chicago
3    David   33      Houston

In [ ]:
df.drop(2, axis=0, inplace=True)  # remove third row index 2
df

    Name  Age         City
0  Alice   25     New York
1    Bob   28  Los Angeles
3  David   33      Houston

In [ ]:
# Read CSV file into DataFrame
df=pd.read_csv('products-100.csv')
df.head(5) # display first 5 rows

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10

In [ ]:
df.describe()  # Get summary statistics of numerical columns

            Index      Price       Stock           EAN  Internal ID
count  100.000000  100.00000  100.000000  1.000000e+02   100.000000
mean    50.500000  451.19000  545.710000  4.876267e+12    49.340000
std     29.011492  281.60911  266.716863  2.918084e+12    28.078253
min      1.000000    1.00000   10.000000  5.246382e+08     3.000000
25%     25.750000  230.75000  347.500000  2.062323e+12    25.000000
50%     50.500000  407.50000  575.500000  4.875720e+12    48.000000
75%     75.250000  679.00000  749.250000  7.676943e+12    74.500000
max    100.000000  999.00000  998.000000  9.921752e+12    99.000000

Data Manipulation and Analysis with Pandas

Data Manipulation and Analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of function for data manipulation and analysis, making it easier to clean, transform and extract insights from data.

In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('data.csv')

In [17]:
df.head(5)  # Display first 5 rows of the DataFrame

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [18]:
# Handling Missing Data
df.isnull()  # Check for missing values in the DataFrame

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [19]:
df.isnull().any()  # Check if any column has missing values

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [20]:
df.isnull().sum()  # Get count of missing values in each column

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [23]:
df.fillna(0)  # Fill missing values with 0

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [24]:
df_filled = df.fillna(0)

In [26]:
# Filling missing values with the mean of the column
df['Sales_FillNA'] = df['Sales'].fillna(df['Sales'].mean()) # Fill missing values in 'Sales' column with the mean of that column
df

          Date Category  Value   Product  Sales Region  Sales_FillNA
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [ ]:
# Rename columns
df = df.rename(columns = {'Date': 'Sales Date'}) # Rename 'Date' column to 'Sales Date'
df.head(5)

   Sales Date Category  Value   Product  Sales Region  Sales_FillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [30]:
# Change data type of a column
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int) # Fill missing values in 'Value' column with the mean and convert to integer
df.head(5)

   Sales Date Category  Value   Product  Sales Region  Sales_FillNA  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [31]:
df['New Value'] = df['Value'].apply(lambda x:x*2) # Multiply each value in 'Value' column by 2 and create a new column 'New Value'
df.head(5)

,Sales Date,Category,Value,Product,Sales,Region,Sales_FillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [32]:
# Data Aggregation and Grouping
grouped_mean = df.groupby('Product')['Value'].mean()  # Calculate mean of 'Value' column grouped by 'Product'
grouped_mean

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [34]:
grouped_sum = df.groupby(['Product', 'Region'])['Value'].sum()  # Calculate sum of 'Value' column grouped by 'Product' and 'Region'
grouped_sum

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [35]:
# Aggregation with multiple functions
grouped_agg = df.groupby(['Region'])['Value'].agg(['mean', 'sum', 'count'])  # Calculate mean, sum, count of 'Value' column grouped by 'Region'
grouped_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17